---
- name: Find the closes apache mirror
  shell: "curl 'https://www.apache.org/dyn/closer.cgi' |  grep -o '<strong>[^<]*</strong>' | sed 's/<[^>]*>//g' | head -1"
  register: apache_mirror
  changed_when: false

- name: Fetch storm package
  get_url: dest={{ download_tmp_dir }}/apache-storm-{{storm_version}}.tar.gz url="{{apache_mirror.stdout}}/storm/apache-storm-{{storm_version}}/apache-storm-{{storm_version}}.tar.gz"
